name: draftai

services:
  triton-server:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file: ./triton.env
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  fastapi:
    build: ./fastapi
    depends_on:
      triton-server:
        condition: service_healthy
    network_mode: "host"
    restart: always

